openapi: 3.0.1
info:
  title: Sorting Algorithm Backend
  license:
    name: Software Engineers Unite
  version: 1.0.0
servers:
  - url: http://localhost:8081/v1
paths:
  /selectionSort:
    post:
      summary: Selection Sort
      requestBody:
        description: selectionsort
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/intArray'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/intArray'
components:
  schemas:
    intArray:
      type: array
      items:
        type: integer
